title: Homepage
description: This is a blog for J.X.Liu to write something interesting he think. Well, I'm a little busy or just lazy, so maybe I sheldom update this blog.
show_downloads: true
google_analytics: sf2r234
theme: jekyll-theme-cayman