title: Lazarus0129's blog
description: Opps! This blog is constructing. This is a blog for J.X.Liu to write something interesting he think. As you see, everything here is void... And I'm a little busy, or just lazy, so maybe I sheldom update this blog. But I'm trying to build this place more comfortable and more substantial. Sorry for that :) 
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman